# Generated by Django 4.2.5 on 2025-06-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='人員編號')),
                ('name_chinese', models.CharField(max_length=50, verbose_name='人員姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性別')),
                ('name_english', models.CharField(max_length=100, verbose_name='英文姓名')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(verbose_name='出生日期')),
                ('military_status', models.CharField(max_length=20, verbose_name='兵役')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='身分證號')),
                ('hire_date', models.DateField(verbose_name='到職日期')),
                ('resignation_date', models.DateField(blank=True, null=True, verbose_name='離職日期')),
                ('title_chinese', models.CharField(max_length=50, verbose_name='中文職稱')),
                ('title_english', models.CharField(max_length=100, verbose_name='英文職稱')),
                ('department', models.CharField(max_length=100, verbose_name='所屬部門')),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3, verbose_name='血型')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_address', models.CharField(max_length=255, verbose_name='聯絡地址')),
                ('household_address', models.CharField(max_length=255, verbose_name='戶籍地址')),
                ('mobile', models.CharField(max_length=20, verbose_name='行動電話')),
                ('telephone', models.CharField(max_length=20, verbose_name='市話')),
                ('emergency_contact_name', models.CharField(max_length=50, verbose_name='緊急聯絡人')),
                ('emergency_contact_address', models.CharField(max_length=255, verbose_name='緊急聯絡人地址')),
                ('emergency_contact_mobile', models.CharField(max_length=20, verbose_name='緊急聯絡人電話')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='緊急聯絡人市話')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='common.employee')),
            ],
        ),
    ]
