# Generated by Django 4.2.5 on 2025-06-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_chinese',
            field=models.CharField(max_length=50, verbose_name='Chinese Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_english',
            field=models.CharField(max_length=100, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='contact_address',
            field=models.CharField(max_length=255, verbose_name='Contact Address'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='emergency_contact_address',
            field=models.CharField(max_length=255, verbose_name='Emergency Contact Address'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='emergency_contact_mobile',
            field=models.CharField(max_length=20, verbose_name='Emergency Contact Mobile'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='emergency_contact_name',
            field=models.CharField(max_length=50, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='emergency_contact_phone',
            field=models.CharField(max_length=20, verbose_name='Emergency Contact Telephone'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='household_address',
            field=models.CharField(max_length=255, verbose_name='Household Address'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3, verbose_name='Blood Type'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='hire_date',
            field=models.DateField(verbose_name='Hire Date'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='military_status',
            field=models.CharField(max_length=20, verbose_name='Military Status'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='resignation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Resignation Date'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='title_chinese',
            field=models.CharField(max_length=50, verbose_name='Title (Chinese)'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='title_english',
            field=models.CharField(max_length=100, verbose_name='Title (English)'),
        ),
    ]
