# Generated by Django 5.2.2 on 2025-06-07 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_employee_employee_id_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Department Code')),
                ('name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('name_en', models.CharField(max_length=100, verbose_name='Department English Name')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Disabled')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='common.department', verbose_name='Parent Department')),
            ],
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.department', verbose_name='Department'),
        ),
    ]
