# Generated by Django 5.2.2 on 2025-06-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_department_alter_employeeprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name_english',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3, null=True, verbose_name='Blood Type'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hire Date'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='military_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Military Status'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='title_chinese',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title (Chinese)'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='title_english',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (English)'),
        ),
    ]
