# Generated by Django 5.2.2 on 2025-06-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_employee_name_english_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontact',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Address'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='emergency_contact_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Emergency Contact Address'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='emergency_contact_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Mobile'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Telephone'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='household_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Household Address'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone'),
        ),
    ]
