# Generated by Django 5.2.2 on 2025-06-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department English Name'),
        ),
    ]
