# Generated by Django 5.2.2 on 2025-06-07 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_department_is_deleted_employee_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='部門編號'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='刪除'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='停用'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='部門名稱'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='部門英文名稱'),
        ),
        migrations.AlterField(
            model_name='department',
            name='note',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='common.department', verbose_name='上層部門'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='人員編號'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='刪除'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_chinese',
            field=models.CharField(max_length=50, verbose_name='人員姓名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_english',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='英文姓名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='帳號'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='聯絡地址'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='emergency_contact_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='緊急聯絡人地址'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='emergency_contact_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='緊急聯絡人電話'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='緊急聯絡人'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='緊急聯絡人市話'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='household_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='戶籍地址'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='行動電話'),
        ),
        migrations.AlterField(
            model_name='employeecontact',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='市話'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3, null=True, verbose_name='血型'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='date_of_birth',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.department', verbose_name='所屬部門'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='到職日期'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='military_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='兵役'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='身分證號'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='resignation_date',
            field=models.DateField(blank=True, null=True, verbose_name='離職日期'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='title_chinese',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='中文職稱'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='title_english',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='英文職稱'),
        ),
    ]
