# Generated by Django 5.2.2 on 2025-06-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_department_code_alter_department_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='倉庫編號')),
                ('name', models.CharField(max_length=100, verbose_name='倉庫名稱')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='倉庫簡稱')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名稱')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='聯絡人員')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='聯絡電話')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='倉庫地址')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='刪除')),
            ],
        ),
    ]
