# Generated by Django 5.2.2 on 2025-06-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='類別編號')),
                ('name', models.CharField(max_length=100, verbose_name='類別名稱')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='刪除')),
            ],
        ),
    ]
