# Generated by Django 5.2.2 on 2025-06-08 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='幣別編號')),
                ('name', models.CharField(max_length=50, verbose_name='幣別名稱')),
                ('short_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='幣別簡稱')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='產品編號')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='國際條碼')),
                ('customer_barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='客戶端條碼')),
                ('name', models.CharField(max_length=200, verbose_name='品名規格')),
                ('invoice_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='發票品名')),
                ('english_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='英文品名')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='計量單位')),
                ('package1_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='包裝1數量')),
                ('package1_unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='包裝1單位')),
                ('package2_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='包裝2數量')),
                ('package2_unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='包裝2單位')),
                ('msrp', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='建議售價')),
                ('price_a', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='售價A')),
                ('price_b', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='售價B')),
                ('price_c', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='售價C')),
                ('price_d', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='售價D')),
                ('price_e', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='售價E')),
                ('standard_cost', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='標準進價')),
                ('cost_rmb', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, verbose_name='人民幣進價')),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, verbose_name='美金進價')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='刪除')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.productcategory', verbose_name='產品類別')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.currency', verbose_name='使用幣別')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_stock', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, verbose_name='安全存量')),
                ('opening_stock', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, verbose_name='期初存量')),
                ('current_stock', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, verbose_name='現有數量')),
                ('real_stock', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, verbose_name='實際在庫量')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.product', verbose_name='產品')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.warehouse', verbose_name='倉庫編號')),
            ],
        ),
    ]
