# Generated by Django 5.2.2 on 2025-06-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_currency_product_productstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='刪除'),
        ),
    ]
