# Generated by Django 5.2.2 on 2025-06-08 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_currency_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_suffix', models.CharField(max_length=10, verbose_name='子項代碼')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='變化名稱')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='變化值')),
                ('display_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='顯示用編號')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='common.product', verbose_name='主商品')),
            ],
            options={
                'verbose_name': '產品變化明細',
                'verbose_name_plural': '產品變化明細',
                'unique_together': {('product', 'code_suffix')},
            },
        ),
    ]
