# Generated by Django 5.2.2 on 2025-06-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_productdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='display_code',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='note',
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='code_suffix',
            field=models.CharField(max_length=10, verbose_name='型號'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='型號名稱'),
        ),
    ]
