# Generated by Django 5.2.2 on 2025-06-11 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_remove_productdetail_display_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='代碼')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵遞區號')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='聯絡人')),
                ('contact_title', models.CharField(blank=True, max_length=50, verbose_name='聯絡人職稱')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='電話')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='傳真')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='代碼')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='MemberLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='代碼')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='代碼')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='卡號')),
                ('national_id', models.CharField(max_length=20, verbose_name='身分證號')),
                ('issue_date', models.DateField(verbose_name='發卡日期')),
                ('gender', models.CharField(max_length=10, verbose_name='性別')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵遞區號')),
                ('home_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_members', to='common.address', verbose_name='戶籍地址')),
                ('household_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_members', to='common.address', verbose_name='居住地址')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.memberlevel', verbose_name='會員等級')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='客戶代碼')),
                ('full_name', models.CharField(max_length=100, verbose_name='客戶全名')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='簡稱')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='統一編號')),
                ('invoice_title', models.CharField(blank=True, max_length=100, verbose_name='發票抬頭')),
                ('responsible_person', models.CharField(blank=True, max_length=50, verbose_name='負責人')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='聯絡人')),
                ('phone1', models.CharField(blank=True, max_length=30, verbose_name='電話1')),
                ('phone2', models.CharField(blank=True, max_length=30, verbose_name='電話2')),
                ('phone3', models.CharField(blank=True, max_length=30, verbose_name='電話3')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='手機')),
                ('fax', models.CharField(blank=True, max_length=30, verbose_name='傳真')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('website', models.URLField(blank=True, verbose_name='網站')),
                ('last_sale_date', models.DateField(blank=True, null=True, verbose_name='最後銷貨日期')),
                ('last_return_date', models.DateField(blank=True, null=True, verbose_name='最後退貨日期')),
                ('price_mode', models.CharField(blank=True, choices=[('no_tax', '未稅'), ('tax', '含稅')], max_length=10, verbose_name='價格模式')),
                ('tax_type', models.CharField(blank=True, choices=[('taxable', '應稅'), ('exempt', '免稅'), ('zero', '零稅'), ('blank', '空白'), ('no_invoice', '免開')], max_length=10, verbose_name='課稅類別')),
                ('customer_type', models.CharField(blank=True, max_length=50, verbose_name='客戶類型')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency', verbose_name='幣別')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_customers', to='common.address', verbose_name='送貨地址')),
                ('invoice_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_customers', to='common.address', verbose_name='發票地址')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.employee', verbose_name='業務人員')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.customercategory', verbose_name='客戶類別')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.member', verbose_name='會員')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='廠商編號')),
                ('full_name', models.CharField(max_length=100, verbose_name='廠商全稱')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='廠商簡稱')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='統一編號')),
                ('invoice_title', models.CharField(blank=True, max_length=100, verbose_name='發票抬頭')),
                ('responsible_person', models.CharField(blank=True, max_length=50, verbose_name='負責人')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='聯絡人')),
                ('phone1', models.CharField(blank=True, max_length=30, verbose_name='聯絡電話一')),
                ('phone2', models.CharField(blank=True, max_length=30, verbose_name='聯絡電話二')),
                ('phone3', models.CharField(blank=True, max_length=30, verbose_name='聯絡電話三')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='行動電話')),
                ('fax', models.CharField(blank=True, max_length=30, verbose_name='傳真號碼')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('website', models.URLField(blank=True, verbose_name='網站')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='最近進貨日')),
                ('last_return_date', models.DateField(blank=True, null=True, verbose_name='最近退貨日')),
                ('price_mode', models.CharField(blank=True, choices=[('no_tax', '未稅'), ('tax', '含稅')], max_length=10, verbose_name='產品單價')),
                ('tax_type', models.CharField(blank=True, choices=[('taxable', '應稅'), ('exempt', '免稅'), ('zero', '零稅'), ('blank', '空白'), ('no_invoice', '免開')], max_length=10, verbose_name='課稅類別')),
                ('supplier_type', models.CharField(blank=True, max_length=50, verbose_name='廠商類型')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.currency', verbose_name='幣別')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_suppliers', to='common.address', verbose_name='送貨地址')),
                ('invoice_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_suppliers', to='common.address', verbose_name='發票地址')),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.employee', verbose_name='採購員')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.suppliercategory', verbose_name='廠商類別')),
            ],
        ),
    ]
