# Generated by Django 5.2.2 on 2025-06-11 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_address_customercategory_memberlevel_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '地址', 'verbose_name_plural': '地址'},
        ),
        migrations.AddField(
            model_name='address',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='內容類型'),
        ),
        migrations.AddField(
            model_name='address',
            name='object_id',
            field=models.PositiveIntegerField(null=True, verbose_name='對象ID'),
        ),
    ]
