# Generated by Django 5.2.2 on 2025-07-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='稅率'),
        ),
    ]
