# Generated by Django 5.2.2 on 2025-08-24 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_currency_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='opening_stock',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='real_stock',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='safe_stock',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='國際條碼'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='ProductDetail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.productdetail', verbose_name='產品型號'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstock',
            name='booked_stock',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, verbose_name='已留貨數量'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='free_stock',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, verbose_name='可用數量'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='unarrived_stock',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True, verbose_name='未到貨數量'),
        ),
    ]
