# Generated by Django 5.2.2 on 2025-08-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_remove_product_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='barcode',
            field=models.CharField(max_length=50, verbose_name='國際條碼'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='code_suffix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='型號'),
        ),
    ]
