# Generated by Django 5.2.2 on 2025-10-28 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_alter_productdetail_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='employee',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='dept_name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='code',
            new_name='dept_no',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='parent',
            new_name='parent_dept',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name_chinese',
            new_name='employee_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name_english',
        ),
        migrations.AddField(
            model_name='employee',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='出生日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3, null=True, verbose_name='血型'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contact_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='聯絡地址'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.department', verbose_name='所屬部門'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='jason@mail.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='緊急聯絡人地址'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='緊急聯絡人電話'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='緊急聯絡人'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='緊急聯絡人市話'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='到職日期'),
        ),
        migrations.AddField(
            model_name='employee',
            name='household_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='戶籍地址'),
        ),
        migrations.AddField(
            model_name='employee',
            name='military_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='兵役'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(default='0912345678', max_length=20, verbose_name='行動電話'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(default='A123456789', max_length=20, unique=True, verbose_name='身分證號'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='resignation_date',
            field=models.DateField(blank=True, null=True, verbose_name='離職日期'),
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='市話'),
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='職稱'),
        ),
        migrations.DeleteModel(
            name='EmployeeContact',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
