# Generated by Django 5.2.2 on 2025-11-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_remove_employeeprofile_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='employee_no',
        ),
    ]
