# Generated by Django 5.2.2 on 2025-06-14 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0018_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='採購日期')),
                ('voucher_number', models.CharField(max_length=20, unique=True, verbose_name='單據號碼')),
                ('status', models.CharField(choices=[('open', '未結案'), ('closed', '已結案'), ('invalid', '無效')], default='open', max_length=10, verbose_name='單況')),
                ('price_mode', models.CharField(blank=True, choices=[('no_tax', '未稅'), ('tax', '含稅')], max_length=10, verbose_name='價格模式')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_vouchers', to='common.employee', verbose_name='製單人員')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.currency', verbose_name='幣別')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_vouchers', to='common.employee', verbose_name='採購人員')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_purchase_vouchers', to='common.employee', verbose_name='覆核人員')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.supplier', verbose_name='廠商')),
                ('supplier_address', models.ForeignKey(limit_choices_to={'content_type__model': 'supplier'}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_vouchers', to='common.address', verbose_name='廠商地址')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseVoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='單價')),
                ('discount', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='折數')),
                ('unreceived_quantity', models.PositiveIntegerField(default=0, verbose_name='未進貨數量')),
                ('is_gift', models.BooleanField(default=False, verbose_name='是否為贈品')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.product', verbose_name='產品')),
                ('purchase_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.purchasevoucher')),
            ],
        ),
    ]
