# Generated by Django 5.2.2 on 2025-07-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('taxable', '應稅'), ('exempt', '免稅'), ('zero', '零稅'), ('blank', '空白'), ('no_invoice', '免開')], max_length=10, verbose_name='課稅類別'),
        ),
    ]
